# Generating Simple Embendding

In [1]:
import os
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv(), override=True)

True

In [2]:
from openai import OpenAI
client = OpenAI()

In [8]:
text=''' This is a random text
OpenAI o3 is a GPT model developed by OpenAI
'''


text = text.replace('\n', ' ')

emd = client.embeddings.create(
    input=text,
    model='text-embedding-3-small'
)

print(emd.data[0].embedding)

CreateEmbeddingResponse(data=[Embedding(embedding=[-0.02166748046875, 0.020904541015625, 0.046875, -0.0236358642578125, 0.003246307373046875, -0.054443359375, -0.01425933837890625, 0.0181732177734375, -0.0007915496826171875, -0.017486572265625, 0.03485107421875, -0.004306793212890625, -0.01837158203125, 0.0094757080078125, -0.0239410400390625, -0.0139923095703125, -0.0195770263671875, -0.09002685546875, -0.039306640625, 0.0013523101806640625, 0.0256500244140625, 0.0229034423828125, 0.00798797607421875, -0.015167236328125, 0.0116729736328125, 0.003917694091796875, 0.0206451416015625, 0.0239410400390625, 0.006877899169921875, -0.0333251953125, 0.033416748046875, -0.0238800048828125, -0.07525634765625, -1.1980533599853516e-05, -0.021148681640625, -0.00046181678771972656, -0.005756378173828125, 0.018951416015625, -0.0213775634765625, 0.036285400390625, 0.0012683868408203125, -0.01551055908203125, -0.00551605224609375, 0.033721923828125, -0.0171051025390625, 0.0109100341796875, 0.020538330078125, 0.01229095458984375, -0.0126495361328125, 0.031463623046875, -0.026031494140625, 0.05914306640625, -0.0167999267578125, 0.0125732421875, -0.0244903564453125, -0.013214111328125, -0.00916290283203125, 0.03961181640625, -0.0101470947265625, -0.0146636962890625, -0.041656494140625, -0.00899505615234375, 0.02508544921875, 0.07354736328125, 0.0119171142578125, -0.0237884521484375, -0.017547607421875, 0.0489501953125, 0.0006060600280761719, -0.01413726806640625, -0.03680419921875, 0.009185791015625, -0.0413818359375, -0.02899169921875, -0.00243377685546875, -0.02923583984375, -0.032440185546875, 0.03057861328125, -0.0284423828125, -0.0362548828125, 0.0001875162124633789, 0.032073974609375, 0.0018596649169921875, -0.046356201171875, -0.004421234130859375, -0.03192138671875, -0.053192138671875, 0.0174407958984375, -0.0360107421875, -0.01702880859375, -0.058868408203125, -0.01238250732421875, -0.0325927734375, -0.0147857666015625, -0.0075225830078125, -0.0191802978515625, -0.01010894775390625, -0.005908966064453125, 0.015167236328125, 0.00618743896484375, -0.055419921875, 0.00850677490234375, 0.0132904052734375, 0.043212890625, -0.006603240966796875, 0.0264129638671875, -0.0016307830810546875, -0.03033447265625, -0.0103607177734375, 0.0030078887939453125, -0.09136962890625, 0.00708770751953125, 0.011383056640625, 0.01314544677734375, 0.0020809173583984375, 0.006694793701171875, 0.03839111328125, 0.0178375244140625, 0.0204620361328125, -0.0689697265625, 0.0164794921875, 0.0290374755859375, 0.006938934326171875, -0.004924774169921875, -0.016571044921875, 0.005950927734375, 0.0194244384765625, -0.016082763671875, -0.001628875732421875, 0.004215240478515625, -0.019317626953125, 0.026458740234375, 0.0002130270004272461, -0.03790283203125, -0.005268096923828125, -0.0406494140625, -0.0234375, -0.01074981689453125, -0.036834716796875, 0.0185089111328125, -0.00283050537109375, -0.01494598388671875, -0.040069580078125, -0.00366973876953125, -0.0182037353515625, -0.049713134765625, 0.02032470703125, -0.04254150390625, 0.00843048095703125, 0.0034694671630859375, -0.06341552734375, 0.046630859375, -0.01300811767578125, -0.017181396484375, 0.00742340087890625, -0.034210205078125, 0.029754638671875, 0.040191650390625, 0.06890869140625, -0.0136566162109375, -0.00482177734375, 0.03173828125, -0.01520538330078125, -0.007297515869140625, -0.01256561279296875, 0.057586669921875, 0.0079345703125, -0.031097412109375, -0.050079345703125, -0.0212860107421875, 0.0262603759765625, 0.0002474784851074219, -0.06353759765625, 0.01076507568359375, -0.02911376953125, 0.00030517578125, -0.039154052734375, 0.041900634765625, -0.0115203857421875, -0.0248565673828125, -0.0040283203125, 0.035736083984375, -0.033721923828125, -0.0014972686767578125, -0.03192138671875, -0.031219482421875, 0.0330810546875, -0.0090179443359375, -0.01488494873046875, 0.033447265625, -0.0094757080078125, 0.006504058837890625, 0.03692626953125, 0.0108184814453125, 0.049652099609375, -0.07275390625, 0.047119140625, -0.03045654296875, 0.04248046875, 0.02667236328125, 0.013458251953125, 0.072998046875, -0.0269775390625, -0.054443359375, 0.018402099609375, -0.017669677734375, 0.0089263916015625, -0.035247802734375, -0.028564453125, -4.297494888305664e-05, 0.0653076171875, -0.04034423828125, -0.017364501953125, -0.0161590576171875, -0.0233306884765625, -0.058807373046875, -0.01235198974609375, 0.026824951171875, 0.0084991455078125, 0.026580810546875, -0.02313232421875, 0.044036865234375, 0.04827880859375, 0.03167724609375, -0.011322021484375, 0.0224456787109375, 0.01389312744140625, -0.0091400146484375, 0.0718994140625, 0.01030731201171875, 0.0138702392578125, -0.006443023681640625, 0.00441741943359375, -0.034027099609375, 0.01229095458984375, -0.0126495361328125, 0.04254150390625, -0.0030078887939453125, -0.036407470703125, -0.01197052001953125, 0.00460052490234375, 0.029754638671875, 0.0516357421875, 0.00885772705078125, 0.0290069580078125, -0.0087738037109375, 0.01364898681640625, -0.019989013671875, 0.0227508544921875, 0.0309295654296875, 0.06671142578125, 0.01508331298828125, -0.005733489990234375, -0.0195159912109375, -0.0202789306640625, -0.0212860107421875, 0.01263427734375, 0.04022216796875, -0.014862060546875, -0.064453125, 0.0223388671875, -0.01540374755859375, -0.0518798828125, 0.016204833984375, -0.015167236328125, -0.0186309814453125, -0.0286712646484375, -0.0006861686706542969, -0.03729248046875, -0.00357818603515625, -0.0232696533203125, -0.006305694580078125, 0.01273345947265625, 0.001537322998046875, -0.0521240234375, 0.0221099853515625, -0.003063201904296875, -0.0220184326171875, -0.06573486328125, 0.035675048828125, 0.0015163421630859375, 0.031524658203125, 0.047088623046875, 0.044830322265625, -0.019256591796875, -0.005035400390625, -0.004825592041015625, -0.0139923095703125, -0.0169830322265625, 0.00432586669921875, 0.017364501953125, -0.05059814453125, 0.05596923828125, 0.0271148681640625, 0.0012083053588867188, -0.0014019012451171875, 0.036865234375, 0.005245208740234375, -0.0227813720703125, 0.00893402099609375, 0.049041748046875, 0.00438690185546875, 0.00499725341796875, 0.026214599609375, 0.01122283935546875, 0.056549072265625, 0.020416259765625, 0.00638580322265625, 0.0291290283203125, 0.0239715576171875, -0.034393310546875, 0.0233917236328125, 0.01314544677734375, -0.0037555694580078125, -0.0308074951171875, -0.008056640625, 0.0229339599609375, 0.00408172607421875, 0.02386474609375, -0.032257080078125, -0.01137542724609375, -0.03814697265625, 0.012481689453125, -0.019683837890625, -0.038360595703125, 0.0016241073608398438, 0.055328369140625, 0.042816162109375, -0.0242462158203125, 0.003978729248046875, 0.01482391357421875, -0.0009927749633789062, 0.01280975341796875, -0.0159759521484375, 0.038116455078125, 0.025146484375, -0.01053619384765625, 0.07318115234375, 0.05865478515625, -0.01100921630859375, -0.0682373046875, -0.0105133056640625, -0.007110595703125, 0.03021240234375, -0.038665771484375, 0.020751953125, -0.0224456787109375, 0.015167236328125, 0.0626220703125, -0.018096923828125, 0.0180206298828125, -0.0021152496337890625, 0.0023555755615234375, -0.038238525390625, -0.00565338134765625, -0.0031833648681640625, 0.00934600830078125, 0.0159149169921875, 0.02099609375, -0.01212310791015625, -0.0247344970703125, 0.0283966064453125, -0.01326751708984375, 0.005809783935546875, 0.051544189453125, -0.003429412841796875, -0.01406097412109375, 0.0141754150390625, -0.04229736328125, -0.0257720947265625, -0.03765869140625, 0.00865936279296875, -0.013519287109375, -0.00821685791015625, -0.0482177734375, -0.008209228515625, -0.01053619384765625, 0.0035800933837890625, -0.0183563232421875, 0.0570068359375, -0.00688934326171875, 0.0085296630859375, -0.02972412109375, 0.00168609619140625, 0.0216827392578125, -0.031707763671875, 0.01806640625, -0.0220794677734375, -0.033477783203125, -0.002498626708984375, 0.05596923828125, -0.01654052734375, -0.01097869873046875, 0.02557373046875, 0.002079010009765625, 0.027587890625, 0.0208587646484375, 0.0014257431030273438, 0.00322723388671875, 0.01355743408203125, 0.0137176513671875, 0.0045166015625, -0.0540771484375, 0.032257080078125, -0.0206146240234375, 0.0252227783203125, 0.055267333984375, 0.029327392578125, 0.0174560546875, -0.0178070068359375, 0.07861328125, -0.05743408203125, 0.013214111328125, -0.014801025390625, 0.059295654296875, -0.01381683349609375, 0.005580902099609375, -0.008026123046875, -0.0024280548095703125, 0.0689697265625, -0.01434326171875, -0.018157958984375, -0.0204925537109375, -0.0165557861328125, -0.005558013916015625, 0.0345458984375, 0.0653076171875, -0.009002685546875, -0.044036865234375, -0.0225982666015625, -0.00518035888671875, 0.0009264945983886719, -0.06561279296875, 0.005321502685546875, 0.0186767578125, 0.0009965896606445312, 0.006122589111328125, -0.00621795654296875, -0.002422332763671875, 0.007228851318359375, 0.041961669921875, 0.0330810546875, -0.0572509765625, -0.00940704345703125, -0.03448486328125, -0.033203125, -0.0190277099609375, -0.0264129638671875, -0.0233001708984375, -0.0186920166015625, -0.01203155517578125, -0.0286865234375, 0.0220489501953125, 0.00021898746490478516, -0.01049041748046875, -0.035003662109375, 0.054840087890625, -0.0003898143768310547, 0.036590576171875, 0.033050537109375, 0.022308349609375, -0.024505615234375, -0.013031005859375, -0.0125732421875, 0.006336212158203125, -0.01300811767578125, -0.0216827392578125, 0.04180908203125, 0.0140380859375, 0.01551055908203125, -0.007198333740234375, 0.01261138916015625, 0.01459503173828125, -0.034515380859375, 0.01739501953125, -0.053955078125, 0.0361328125, -0.00794219970703125, -0.0282745361328125, 0.013519287109375, 0.01947021484375, 0.005756378173828125, -0.0202789306640625, -0.01343536376953125, -0.00501251220703125, -0.0295562744140625, -0.0105438232421875, -0.0005636215209960938, 0.02471923828125, -0.0224761962890625, -0.0029773712158203125, -0.00457763671875, -0.014495849609375, -0.01177215576171875, 0.0654296875, 0.017181396484375, 0.005245208740234375, -0.0626220703125, -0.047760009765625, -0.01412200927734375, -0.0037059783935546875, -0.0201416015625, -0.01239013671875, -0.003635406494140625, 0.00885009765625, -0.0155029296875, 0.017425537109375, -0.0274810791015625, 0.015655517578125, 0.0045166015625, -0.009185791015625, -0.0182952880859375, 0.00638580322265625, -0.024810791015625, 0.0002982616424560547, -0.0024890899658203125, -0.006927490234375, 0.07550048828125, 0.01849365234375, 0.0052947998046875, 0.01093292236328125, 0.028228759765625, -0.006130218505859375, -0.026092529296875, -0.00655364990234375, -0.049163818359375, -0.02581787109375, -0.0758056640625, -0.01070404052734375, 0.0099945068359375, 0.0210113525390625, -0.0233154296875, 0.045562744140625, 0.004241943359375, -0.0791015625, -0.00881195068359375, 0.0224151611328125, -0.007266998291015625, -0.0104522705078125, 0.01035308837890625, -2.0265579223632812e-06, 0.052764892578125, 0.00742340087890625, 0.021087646484375, -0.03692626953125, 0.02001953125, 0.01558685302734375, -0.016815185546875, 0.0082550048828125, 0.0303192138671875, 0.0677490234375, 0.0233154296875, 0.004405975341796875, -0.035919189453125, 0.014312744140625, -0.0001475811004638672, 0.0168609619140625, -0.00077056884765625, 0.03173828125, 0.0309600830078125, 0.00930023193359375, -0.015655517578125, -0.0019054412841796875, 0.0195770263671875, -0.0012540817260742188, 0.0134735107421875, -0.01165771484375, 0.0142974853515625, 0.0234375, -0.01262664794921875, -0.006229400634765625, 0.0328369140625, -0.00945281982421875, 0.036651611328125, -0.00829315185546875, -0.01082611083984375, 0.04779052734375, 0.01253509521484375, -0.0159149169921875, 0.0269927978515625, -0.003387451171875, -0.00818634033203125, 0.0188140869140625, -0.0026683807373046875, -0.03167724609375, 0.03033447265625, 0.037353515625, 0.0292816162109375, -0.01111602783203125, 0.0233154296875, 0.0294342041015625, -0.022735595703125, -0.01824951171875, -0.050140380859375, -0.0161590576171875, -0.056793212890625, 0.00934600830078125, -0.015960693359375, -0.01071929931640625, -0.0047149658203125, 0.0247955322265625, -0.012451171875, -0.00213623046875, 0.041534423828125, -0.02105712890625, 0.026031494140625, -0.03802490234375, -0.040435791015625, 0.00907135009765625, -0.001811981201171875, 0.0004284381866455078, 0.00965118408203125, -0.00251007080078125, -0.0201416015625, -0.0118408203125, -0.0137939453125, -0.006603240966796875, 0.02264404296875, 0.06329345703125, 0.02679443359375, -0.0187225341796875, 0.0274810791015625, 0.03314208984375, -0.01351165771484375, -0.038909912109375, 0.01001739501953125, -0.0019969940185546875, 0.024322509765625, -0.01910400390625, 0.0301666259765625, 0.00749969482421875, -0.007389068603515625, 0.01153564453125, -0.009674072265625, -0.0006470680236816406, 0.00923919677734375, -0.007640838623046875, -0.02191162109375, -0.0125732421875, -0.039794921875, -0.006793975830078125, 0.029876708984375, 0.0014591217041015625, 0.00095367431640625, 0.047271728515625, 0.0294036865234375, -0.0243682861328125, 0.015716552734375, -0.00823211669921875, -0.037261962890625, 0.005939483642578125, -0.035552978515625, -0.0228729248046875, 0.060821533203125, -0.01202392578125, -0.030242919921875, -0.01184844970703125, -0.00030231475830078125, 0.017578125, 0.00724029541015625, -0.065185546875, -0.01314544677734375, 0.032073974609375, 0.0065460205078125, -0.0211334228515625, 0.055023193359375, -0.043609619140625, 0.014739990234375, 0.011505126953125, -0.00041985511779785156, -0.0133514404296875, -0.0274200439453125, 0.0322265625, -0.0225067138671875, 0.049530029296875, 0.0035858154296875, 0.01560211181640625, -0.0518798828125, -0.027740478515625, -0.0235137939453125, -0.0016765594482421875, 0.0303192138671875, -0.027557373046875, 0.022552490234375, 0.0301361083984375, 0.02081298828125, 0.033050537109375, 0.00811767578125, -0.00943756103515625, -0.03143310546875, -0.0180511474609375, 0.007297515869140625, 0.017486572265625, 0.02105712890625, 0.036895751953125, -0.03326416015625, 0.015045166015625, 0.0104827880859375, -0.02520751953125, -0.004787445068359375, -0.01629638671875, 0.0218505859375, -0.01282501220703125, -0.00921630859375, 0.01849365234375, -0.0094451904296875, 0.007511138916015625, 0.0304412841796875, 0.0179901123046875, 0.0176239013671875, -0.020965576171875, 0.005157470703125, 0.023529052734375, 0.030517578125, 0.00839996337890625, -0.0153656005859375, 0.035430908203125, -0.007049560546875, -0.037078857421875, -0.005893707275390625, -0.025146484375, 0.02142333984375, 0.00399017333984375, -0.0231170654296875, -0.0203704833984375, -0.077880859375, -0.0194549560546875, -0.029632568359375, -0.049072265625, 0.0132293701171875, 0.019287109375, -0.0127716064453125, 0.031585693359375, -0.0246734619140625, 0.01325225830078125, 0.032745361328125, -0.049896240234375, -0.01459503173828125, -0.027435302734375, 0.0012264251708984375, 0.0123138427734375, -0.03436279296875, 0.0129547119140625, 0.0297698974609375, -0.004489898681640625, -0.003444671630859375, 0.0288848876953125, 0.035125732421875, 0.01314544677734375, -0.017913818359375, -6.645917892456055e-05, 0.00930023193359375, -0.021270751953125, -0.0023975372314453125, -0.034149169921875, -0.0149383544921875, 0.017822265625, 0.0118255615234375, -0.0004551410675048828, 0.005584716796875, 0.03759765625, 0.017181396484375, 0.01023101806640625, 0.05767822265625, -0.0263824462890625, -0.022430419921875, -0.003604888916015625, 0.017608642578125, 0.01282501220703125, 0.016876220703125, 0.04888916015625, 0.0007443428039550781, 0.0033130645751953125, 0.0168914794921875, 0.031463623046875, -0.0177459716796875, -0.003765106201171875, -0.0030574798583984375, 0.00402069091796875, -0.0110931396484375, 0.01001739501953125, 0.032073974609375, 0.002834320068359375, 0.002773284912109375, -0.006694793701171875, -0.0307159423828125, 0.0020503997802734375, -0.005451202392578125, -0.036651611328125, -0.027740478515625, -0.0258941650390625, -0.002857208251953125, 0.0316162109375, -0.01953125, -0.001880645751953125, -0.0013456344604492188, 0.0016946792602539062, -0.07037353515625, 0.0174713134765625, 0.01343536376953125, 0.01514434814453125, 0.015380859375, 0.004825592041015625, 0.02984619140625, 0.027618408203125, 0.0005235671997070312, -0.0071868896484375, 0.05712890625, -0.0191650390625, -0.0147247314453125, 0.016387939453125, 0.033477783203125, -0.031463623046875, 0.0065460205078125, -0.008209228515625, -0.01314544677734375, -0.001590728759765625, 0.00595855712890625, 0.005397796630859375, 0.0330810546875, 0.016815185546875, -0.0574951171875, 0.01293182373046875, 0.015655517578125, 0.053802490234375, -0.00418853759765625, 0.0021038055419921875, -0.0192413330078125, -0.005275726318359375, 0.05792236328125, 0.034027099609375, -0.0125732421875, -0.0112457275390625, -0.00605010986328125, -0.0097198486328125, 0.019195556640625, -0.00925445556640625, 0.0273895263671875, -0.03759765625, 0.01285552978515625, -0.0059051513671875, -0.0113677978515625, -0.01190948486328125, 0.03289794921875, -0.0294036865234375, -0.02703857421875, -0.03631591796875, 0.0323486328125, 0.0318603515625, 0.01043701171875, -0.0226593017578125, 0.0011758804321289062, -0.00698089599609375, -0.00885772705078125, 0.01041412353515625, 0.011199951171875, -0.03271484375, -0.00676727294921875, 0.006443023681640625, -0.016021728515625, -0.0020847320556640625, 0.007137298583984375, -0.0006384849548339844, 0.02667236328125, 0.04522705078125, -0.032806396484375, -0.057586669921875, -0.0178070068359375, -0.01232147216796875, 0.027618408203125, 0.0099639892578125, 0.006023406982421875, -0.048309326171875, -0.005748748779296875, 0.057891845703125, 0.015838623046875, -0.0292816162109375, 0.008575439453125, -0.0147247314453125, -0.0231170654296875, 0.00629425048828125, 0.007266998291015625, 0.023773193359375, 0.0159759521484375, -0.04058837890625, -0.04705810546875, 0.01531982421875, 0.005344390869140625, -0.0038318634033203125, 0.004039764404296875, -0.00904083251953125, -0.040679931640625, -0.0009036064147949219, -0.0218963623046875, 0.01910400390625, 0.0008635520935058594, -0.00475311279296875, 0.0310211181640625, -0.004497528076171875, -0.041290283203125, -0.0112457275390625, 0.0026645660400390625, 0.047698974609375, -0.026824951171875, -0.00833892822265625, -0.004184722900390625, -0.01528167724609375, -0.006195068359375, -0.0174102783203125, 0.01995849609375, 0.0189666748046875, 0.021331787109375, 0.005214691162109375, 0.057769775390625, 0.0279998779296875, -0.00496673583984375, -0.02655029296875, -0.0181884765625, -0.03497314453125, -0.00030231475830078125, -0.0020694732666015625, -0.044464111328125, 0.0235137939453125, -0.0169525146484375, 0.00980377197265625, -0.00905609130859375, 0.012664794921875, 0.00870513916015625, -0.028839111328125, -0.015655517578125, 0.032073974609375, -0.057891845703125, -0.022979736328125, -0.01329803466796875, 0.03424072265625, 0.021759033203125, 0.0087432861328125, 0.020843505859375, -0.02685546875, 0.0272674560546875, -0.0139312744140625, -0.0018253326416015625, -0.020843505859375, -0.0007333755493164062, -0.00688934326171875, -0.003498077392578125, 0.0166168212890625, 0.0303192138671875, 0.007080078125, -0.0183258056640625, 0.00786590576171875, -0.00720977783203125, -0.004016876220703125, 0.00954437255859375, 0.00041103363037109375, -0.034332275390625, 0.037841796875, 0.0318603515625, 0.0268707275390625, -0.0062713623046875, 0.00518035888671875, 0.048797607421875, -0.0265350341796875, 0.0014486312866210938, -0.0159912109375, -0.023956298828125, 0.06317138671875, -0.0225830078125, 0.0178070068359375, 0.022064208984375, -0.0225982666015625, -0.004955291748046875, -0.02923583984375, -0.0017242431640625, 0.0212249755859375, 0.01183319091796875, 0.06634521484375, 0.024566650390625, -0.003559112548828125, -0.00559234619140625, 0.004150390625, 0.01611328125, -0.0220184326171875, -0.014923095703125, 0.032470703125, -0.004665374755859375, 0.061279296875, -0.00899505615234375, -0.0129241943359375, -0.0031032562255859375, 0.019

In [9]:
pip install pandas numpy -q

Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd
df=pd.read_csv('words.csv')
df=df.sample(frac=1)
df

        word
1     banana
9       data
0      apple
8       text
7      model
6     vector
2   computer
3     python
4     openai
5  embedding

def get_embendding(text, model='text-embedding-3-small'):
    client = OpenAI()
    text = text.replace('\n', ' ')

    emd = client.embeddings.create(
        input=text,
        model='text-embedding-3-small'
    )

    return emd.data[0].embedding

In [14]:
df['embedding']=df['word'].apply(lambda x: get_embendding(x))
df

        word                                          embedding
1     banana  [0.00855255126953125, -0.0240631103515625, -0....
9       data  [0.0243682861328125, 0.012298583984375, 0.0289...
0      apple  [0.0176544189453125, -0.0168609619140625, -0.0...
8       text  [-0.005947113037109375, 0.029541015625, -0.038...
7      model  [-0.00667572021484375, 0.0031375885009765625, ...
6     vector  [-0.007465362548828125, 0.0069427490234375, -0...
2   computer  [-0.0109100341796875, 0.0078277587890625, -0.0...
3     python  [-0.01039886474609375, -0.012481689453125, 0.0...
4     openai  [0.00598907470703125, -0.00870513916015625, 0....
5  embedding  [-0.0070037841796875, 0.0122833251953125, 0.03...

In [15]:
df.to_csv('words-embenddings.csv',index=False)

## Estimating Embendding Cost with tiktokem

In [16]:
pip install tiktoken -q

Note: you may need to restart the kernel to use updated packages.

In [18]:
import tiktoken
import pandas as pd
df=pd.read_csv('words-embenddings.csv')

In [19]:
df

        word                                          embedding
0     banana  [0.00855255126953125, -0.0240631103515625, -0....
1       data  [0.0243682861328125, 0.012298583984375, 0.0289...
2      apple  [0.0176544189453125, -0.0168609619140625, -0.0...
3       text  [-0.005947113037109375, 0.029541015625, -0.038...
4      model  [-0.00667572021484375, 0.0031375885009765625, ...
5     vector  [-0.007465362548828125, 0.0069427490234375, -0...
6   computer  [-0.0109100341796875, 0.0078277587890625, -0.0...
7     python  [-0.01039886474609375, -0.012481689453125, 0.0...
8     openai  [0.00598907470703125, -0.00870513916015625, 0....
9  embedding  [-0.0070037841796875, 0.0122833251953125, 0.03...

In [22]:
words=list(df['word'])
enc=tiktoken.encoding_for_model('text-embedding-3-small')
total_token=sum([len(enc.encode(word)) for word in words])
print(f'Total Tokens: {total_token}')

Total Tokens: 11

In [24]:
cost_per_token=0.02/1_000_000
est_cost=total_token * cost_per_token
print(f'est total cost {est_cost: .10f}')

est total cost  0.0000002200

## Performing Semantic Searches

In [28]:
pip install -q numpy

Note: you may need to restart the kernel to use updated packages.

In [29]:
import  pandas as pd
import numpy as np
df=pd.read_csv('words-embenddings.csv')

In [30]:
df['embedding']=df['embedding'].apply(eval).apply(np.array)

In [32]:
search_term='red'
search_term_vector= get_embendding(search_term)

In [33]:
import numpy as np

def cosine_similarity(vec1, vec2):
    vec1 = np.array(vec1)
    vec2 = np.array(vec2)

    return np.dot(vec1, vec2) / (
        np.linalg.norm(vec1) * np.linalg.norm(vec2)
    )

In [36]:
df['similar']=  df['embedding'].apply(lambda x: cosine_similarity(x, search_term_vector))
df.sort_values('similar', ascending=False)

        word                                          embedding   similar
2      apple  [0.0176544189453125, -0.0168609619140625, -0.0...  0.324858
4      model  [-0.00667572021484375, 0.0031375885009765625, ...  0.322956
5     vector  [-0.007465362548828125, 0.0069427490234375, -0...  0.305788
1       data  [0.0243682861328125, 0.012298583984375, 0.0289...  0.302794
3       text  [-0.005947113037109375, 0.029541015625, -0.038...  0.268638
0     banana  [0.00855255126953125, -0.0240631103515625, -0....  0.242090
6   computer  [-0.0109100341796875, 0.0078277587890625, -0.0...  0.229030
8     openai  [0.00598907470703125, -0.00870513916015625, 0....  0.228124
9  embedding  [-0.0070037841796875, 0.0122833251953125, 0.03...  0.180889
7     python  [-0.01039886474609375, -0.012481689453125, 0.0...  0.170303

In [37]:
v1= df['embedding'].iloc[4]
v2= df['embedding'].iloc[8]
v=v1+v2
v

array([-0.00068665, -0.00556755,  0.01335144, ..., -0.00547791,
       -0.01185608, -0.05653381], shape=(1536,))