In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('traffic_data.csv')
df

        city  volume
0  Ahmedabad  125000
1   Vadodara   85000
2      Surat  110000
3     Rajkot   65000
4     Mumbai  450000
5      Delhi  520000
6  Bengaluru  390000
7       Pune  210000

In [10]:
gp=df.groupby('city')['volume'].agg(['mean'])
gp

               mean
city
Ahmedabad  125000.0
Bengaluru  390000.0
Delhi      520000.0
Mumbai     450000.0
Pune       210000.0
Rajkot      65000.0
Surat      110000.0
Vadodara    85000.0